
       <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">About Website Developer</h2>
            <h3 class="section-subheading text-muted"></h3>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <ul class="timeline">
              <li>
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="img/about/0000.jpg" height= 25% width=25% alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <h4>Wirachai Porien</h4>
                    <h4 class="subheading">Student ID 590610660</h4>
                  </div>
                </div>
              </li>
              <li class="timeline-inverted">
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="img/about/2.png" height= 20% width=20% alt="">
                  <img class="rounded-circle img-fluid" src="img/about/3.jpg" height= 20% width=20% alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <h4>Studying at Chiang Mai University </h4>
                    <h4 class="subheading">Faculty of Engineering Computer Engineering</h4>
                  </div>
                </div>
              </li>
              
            </ul>
          </div>
        </div>
      </div>

   