<div class="container">
        <img class="img-fluid mb-5 d-block mx-auto" src="<?php echo $this->url->getBaseUri(); ?>public/img/Handshake.png" height=50% width= 50% alt="">
        <h1 class="text-uppercase mb-0  text-center">Start Bootstrap</h1>
        <br/><br/><br/><br/><br/><br/><br/><br/>

        <h6>You can contact me on
              <a href="https://www.facebook.com/aef.wirachai">Facebook</a></h6>
</div>